name: Build and Deploy
on:
  push:
    branches:
      - yukanagae-patch-2
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{secrets.SSH_KEY}}
        script: |
          cd /home/flask/flask_project
          git clone git@github.com:yukanagae/lme-digitalocean-docker.git
        context: ./src
        dockerfile: dev.dockerfile
        tty: true
        working_dir: /bot/app
        entrypoint: bash ./entrypoint.dev.sh
        volumes: ./src:/bot
