name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{secrets.SSH_KEY}}
        script: |
          cd /home/flask/flask_project
          git clone git@github.com:yukanagae/lme-digitalocean-docker.git
        context: /home/flask/flask_project/lme-digitalocean-docker/src
        dockerfile: /home/flask/flask_project/lme-digitalocean-docker/scr/dev.dockerfile
        tty: true
        working_dir: /home/flask/flask_project/lme-digitalocean-docker/scr/app
        entrypoint: bash /home/flask/flask_project/lme-digitalocean-docker/scr/app/entrypoint.dev.sh
        volumes: ./src:/bot
