name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: copy git
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{secrets.SSH_KEY}}
        port: ${{ secrets.PORT }}
        script: |
          cd home
          git clone git@github.com:yukanagae/lme-digitalocean-docker.git
    - name: deploy2
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{secrets.SSH_KEY}}
        port: ${{ secrets.PORT }}
        context: /app/lme-digitalocean-docker/src
        dockerfile: /app/lme-digitalocean-docker/scr/dev.dockerfile
        tty: true
        working_dir: /app/lme-digitalocean-docker/scr/app
        entrypoint: bash /app/lme-digitalocean-docker/scr/app/entrypoint.dev.sh
        volumes: /app/lme-digitalocean-docker/src:/bot
